name: use_academy
description: Trilha de Flutter do Use Academy.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  firebase_core: ^1.6.0
  flutter:
    sdk: flutter
  get: ^4.3.8
  google_fonts: ^2.1.0
  http: ^0.13.3
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.2.3

flutter:
  uses-material-design: true

  assets:
    - lib/ui/assets/images/
